/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/core/useGLTF";

export default function CryptoPunkModel(props) {
    const group = useRef();
    const { nodes, materials } = useGLTF("/CryptoPunk.glb");
    return (
        <group ref={group} {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id27.geometry}
                material={materials["1434"]}
                position={[-0.01, 0.28, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id33.geometry}
                material={materials["1436"]}
                position={[-0.02, 0.26, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id39.geometry}
                material={materials["1438"]}
                position={[-0.01, 0.25, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id45.geometry}
                material={materials["1440"]}
                position={[0.08, 0.23, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id51.geometry}
                material={materials["1442"]}
                position={[0.1, 0.2, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id57.geometry}
                material={materials["1444"]}
                position={[-0.05, 0.23, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id63.geometry}
                material={materials["1446"]}
                position={[-0.06, 0.21, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id69.geometry}
                material={materials["1448"]}
                position={[-0.07, 0.19, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id75.geometry}
                material={materials["1450"]}
                position={[-0.05, 0.18, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id81.geometry}
                material={materials["1452"]}
                position={[0.08, 0.18, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id87.geometry}
                material={materials["1454"]}
                position={[-0.08, 0.08, 0.2]}
                scale={[0, 0.01, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id93.geometry}
                material={materials["1456"]}
                position={[0.03, 0.16, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id99.geometry}
                material={materials["1458"]}
                position={[0.11, 0.14, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id105.geometry}
                material={materials["1460"]}
                position={[0.05, 0.13, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id111.geometry}
                material={materials["1462"]}
                position={[0.01, 0.13, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id117.geometry}
                material={materials["1464"]}
                position={[-0.02, 0.11, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id123.geometry}
                material={materials["1466"]}
                position={[0.03, 0.09, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id129.geometry}
                material={materials["1468"]}
                position={[0.08, 0.11, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id135.geometry}
                material={materials["1470"]}
                position={[0.1, 0.07, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id141.geometry}
                material={materials["1472"]}
                position={[0.08, 0.04, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id152.geometry}
                material={materials["1474"]}
                position={[0.06, 0.02, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id158.geometry}
                material={materials["1476"]}
                position={[-0.01, 0.02, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id164.geometry}
                material={materials["1478"]}
                position={[0.03, 0, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id170.geometry}
                material={materials["1480"]}
                position={[0.03, -0.02, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id176.geometry}
                material={materials["1482"]}
                position={[-0.04, 0.01, 0.2]}
                scale={[0, 0.01, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id182.geometry}
                material={materials["1484"]}
                position={[-0.13, 0.02, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id213.geometry}
                material={materials["1486"]}
                position={[0.04, 0.23, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id219.geometry}
                material={materials["1488"]}
                position={[0.04, 0.2, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id225.geometry}
                material={materials["1490"]}
                position={[-0.02, 0.2, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id231.geometry}
                material={materials["1492"]}
                position={[0.03, 0.18, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id237.geometry}
                material={materials["1494"]}
                position={[0.03, 0.13, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id250.geometry}
                material={materials["1496"]}
                position={[0.03, 0.11, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id256.geometry}
                material={materials["1498"]}
                position={[0.06, 0.09, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id262.geometry}
                material={materials["1500"]}
                position={[-0.02, 0.09, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id268.geometry}
                material={materials["1502"]}
                position={[0.02, 0.07, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id274.geometry}
                material={materials["1504"]}
                position={[-0.02, 0.06, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id280.geometry}
                material={materials["1506"]}
                position={[0.07, 0.06, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id286.geometry}
                material={materials["1508"]}
                position={[0.02, 0.04, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id292.geometry}
                material={materials["1510"]}
                position={[0.03, 0.02, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id298.geometry}
                material={materials["1512"]}
                position={[-0.02, 0, 0.2]}
                scale={[0, 0.01, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id304.geometry}
                material={materials["1514"]}
                position={[-0.01, -0.01, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id310.geometry}
                material={materials["1516"]}
                position={[0.01, -0.02, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id340.geometry}
                material={materials["1518"]}
                position={[0.03, 0.06, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id699.geometry}
                material={materials["1520"]}
                position={[-0.02, 0.16, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id721.geometry}
                material={materials["1526"]}
                position={[0.08, 0.16, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id705.geometry}
                material={materials["1522"]}
                position={[-0.02, 0.14, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id722.geometry}
                material={materials["1528"]}
                position={[0.08, 0.14, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id711.geometry}
                material={materials["1524"]}
                position={[-0.02, 0.13, 0.2]}
                scale={[0, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_id723.geometry}
                material={materials["1530"]}
                position={[0.08, 0.13, 0.2]}
                scale={[0, 0, 0]}
            />
        </group>
    );
}

useGLTF.preload("/CryptoPunk.glb");
