/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export default function Model(props) {
    const group = useRef();
    const { nodes, materials } = useGLTF("/dog.glb");
    return (
        <group ref={group} {...props} dispose={null}>
            <group position={[0, 0.01102, -0.05516]} scale={0.30116}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id27.geometry}
                    material={materials["1434"]}
                    position={[-0.00652, 0.28182, 0.19814]}
                    scale={[0.00125, 0.00128, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id33.geometry}
                    material={materials["1436"]}
                    position={[-0.01529, 0.26426, 0.19814]}
                    scale={[0.00252, 0.00129, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id39.geometry}
                    material={materials["1438"]}
                    position={[-0.00651, 0.24692, 0.19814]}
                    scale={[0.00377, 0.00129, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id45.geometry}
                    material={materials["1440"]}
                    position={[0.0801, 0.22961, 0.19814]}
                    scale={[0.00042, 0.00128, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id51.geometry}
                    material={materials["1442"]}
                    position={[0.09726, 0.20378, 0.19814]}
                    scale={[0.00043, 0.00253, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id57.geometry}
                    material={materials["1444"]}
                    position={[-0.0499, 0.22978, 0.19814]}
                    scale={[0.00251, 0.00128, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id63.geometry}
                    material={materials["1446"]}
                    position={[-0.05846, 0.21222, 0.19814]}
                    scale={[0.0021, 0.00128, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id69.geometry}
                    material={materials["1448"]}
                    position={[-0.0672, 0.19488, 0.19814]}
                    scale={[0.00167, 0.00125, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id75.geometry}
                    material={materials["1450"]}
                    position={[-0.04982, 0.17773, 0.19814]}
                    scale={[0.00336, 0.00129, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id81.geometry}
                    material={materials["1452"]}
                    position={[0.08016, 0.17759, 0.19814]}
                    scale={[0.00211, 0.00129, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id87.geometry}
                    material={materials["1454"]}
                    position={[-0.08456, 0.08285, 0.19814]}
                    scale={[0.00168, 0.01276, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id93.geometry}
                    material={materials["1456"]}
                    position={[0.02798, 0.16018, 0.19814]}
                    scale={[0.00126, 0.0013, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id99.geometry}
                    material={materials["1458"]}
                    position={[0.11499, 0.14287, 0.19814]}
                    scale={[0.00042, 0.00379, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id105.geometry}
                    material={materials["1460"]}
                    position={[0.04548, 0.13402, 0.19814]}
                    scale={[0.00042, 0.00253, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id111.geometry}
                    material={materials["1462"]}
                    position={[0.0108, 0.13401, 0.19814]}
                    scale={[0.00042, 0.00253, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id117.geometry}
                    material={materials["1464"]}
                    position={[-0.02364, 0.10831, 0.19814]}
                    scale={[0.00127, 0.00128, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id123.geometry}
                    material={materials["1466"]}
                    position={[0.02773, 0.09104, 0.19814]}
                    scale={[0.00044, 0.00127, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id129.geometry}
                    material={materials["1468"]}
                    position={[0.08052, 0.10831, 0.19814]}
                    scale={[0.00127, 0.00126, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id135.geometry}
                    material={materials["1470"]}
                    position={[0.09774, 0.0738, 0.19814]}
                    scale={[0.00043, 0.00379, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id141.geometry}
                    material={materials["1472"]}
                    position={[0.08035, 0.0393, 0.19814]}
                    scale={[0.00043, 0.00126, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id152.geometry}
                    material={materials["1474"]}
                    position={[0.06264, 0.02198, 0.19814]}
                    scale={[0.00043, 0.00135, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id158.geometry}
                    material={materials["1476"]}
                    position={[-0.00663, 0.02209, 0.19814]}
                    scale={[0.00042, 0.00136, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id164.geometry}
                    material={materials["1478"]}
                    position={[0.02817, 0.00405, 0.19814]}
                    scale={[0.00126, 0.0013, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id170.geometry}
                    material={materials["1480"]}
                    position={[0.02821, -0.02169, 0.19814]}
                    scale={[0.00042, 0.00248, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id176.geometry}
                    material={materials["1482"]}
                    position={[-0.04116, 0.01322, 0.19814]}
                    scale={[0.00042, 0.00762, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id182.geometry}
                    material={materials["1484"]}
                    position={[-0.12795, 0.02154, 0.19814]}
                    scale={[0.00042, 0.00379, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id213.geometry}
                    material={materials["1486"]}
                    position={[0.03662, 0.22947, 0.19814]}
                    scale={[0.00168, 0.00126, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id219.geometry}
                    material={materials["1488"]}
                    position={[0.03655, 0.20369, 0.19814]}
                    scale={[0.0025, 0.00252, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id225.geometry}
                    material={materials["1490"]}
                    position={[-0.02384, 0.19501, 0.19814]}
                    scale={[0.00042, 0.00125, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id231.geometry}
                    material={materials["1492"]}
                    position={[0.02804, 0.17768, 0.19814]}
                    scale={[0.00042, 0.0013, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id237.geometry}
                    material={materials["1494"]}
                    position={[0.02802, 0.13406, 0.19814]}
                    scale={[0.00042, 0.00254, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id250.geometry}
                    material={materials["1496"]}
                    position={[0.02854, 0.10816, 0.19814]}
                    scale={[0.00126, 0.00125, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id256.geometry}
                    material={materials["1498"]}
                    position={[0.06269, 0.09104, 0.19814]}
                    scale={[0.00126, 0.00129, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id262.geometry}
                    material={materials["1500"]}
                    position={[-0.0154, 0.09104, 0.19814]}
                    scale={[0.00168, 0.00126, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id268.geometry}
                    material={materials["1502"]}
                    position={[0.01929, 0.07375, 0.19814]}
                    scale={[0.00336, 0.00126, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id274.geometry}
                    material={materials["1504"]}
                    position={[-0.01529, 0.05621, 0.19814]}
                    scale={[0.00083, 0.00131, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id280.geometry}
                    material={materials["1506"]}
                    position={[0.07134, 0.05631, 0.19814]}
                    scale={[0.00084, 0.00129, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id286.geometry}
                    material={materials["1508"]}
                    position={[0.01956, 0.03937, 0.19814]}
                    scale={[0.00252, 0.0012, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id292.geometry}
                    material={materials["1510"]}
                    position={[0.0279, 0.02227, 0.19814]}
                    scale={[0.00125, 0.00139, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id298.geometry}
                    material={materials["1512"]}
                    position={[-0.02377, -0.00384, 0.19814]}
                    scale={[0.00042, 0.00512, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id304.geometry}
                    material={materials["1514"]}
                    position={[-0.00652, -0.01292, 0.19814]}
                    scale={[0.00043, 0.00377, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id310.geometry}
                    material={materials["1516"]}
                    position={[0.01098, -0.02176, 0.19814]}
                    scale={[0.00042, 0.00248, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id340.geometry}
                    material={materials["1518"]}
                    position={[0.02791, 0.05625, 0.19814]}
                    scale={[0.00126, 0.0013, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id699.geometry}
                    material={materials["1520"]}
                    position={[-0.0239, 0.16008, 0.19814]}
                    scale={[0.00126, 0.00128, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id705.geometry}
                    material={materials["1522"]}
                    position={[-0.02389, 0.14293, 0.19814]}
                    scale={[0.00126, 0.00125, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id711.geometry}
                    material={materials["1524"]}
                    position={[-0.02391, 0.12575, 0.19814]}
                    scale={[0.00126, 0.00128, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id721.geometry}
                    material={materials["1526"]}
                    position={[0.08014, 0.16008, 0.19814]}
                    scale={[0.00128, 0.00128, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id722.geometry}
                    material={materials["1528"]}
                    position={[0.08014, 0.14317, 0.19814]}
                    scale={[0.00128, 0.00128, 0.00127]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_id723.geometry}
                    material={materials["1530"]}
                    position={[0.08014, 0.12575, 0.19814]}
                    scale={[0.00128, 0.00128, 0.00127]}
                />
            </group>
            <PerspectiveCamera
                makeDefault={false}
                far={29.23347}
                near={0.01073}
                fov={35}
                position={[0.0428, 0.07606, 0.23403]}
                rotation={[-0.14329, 0.22668, 0.03242]}
            />
        </group>
    );
}

useGLTF.preload("/dog.glb");
